### ISSUE TITLE
Not able to insert nc files into vw

### ISSUE THREAD

**Issue by lisapalathingal** [tri-state-epscor/wcwave_adaptors#12]
Modify the code to upload files with extension other than 'tif' into VW.

**Comment by mtpain** [comment]
Could you please show me the code you tried to run that failed or tell me if you were using the web app? What file extension were you using? Last time I tried uploading files it worked and I don't think I changed any code.

**Comment by lisapalathingal** [comment]
I used the code from your documentation: http://tri-state-epscor.github.io/vw-doc/

I tried to upload NetCDF file. It didn't upload. I tried uploading tif file and it worked.

Code:

from wcwave_adaptors import VWClient
vw_client = VWClient('https://vwp-dev.unm.edu', username, password)
new_mr_uuid = vw_client.initialize_modelrun(
        model_run_name='PRMS',
        description='PRMS Output File',
        researcher_name='Lisa Palathingal', keywords='prms,example,nevada')
res = vw_client.upload(new_mr_uuid, 'visualizer.csv')
from wcwave_adaptors import make_fgdc_metadata, metadata_from_file

input_file = 'visualizer.csv'
parent_uuid = new_mr_uuid
description = 'prms animation output file'
watershed_name = 'Lehman Creek'
state = 'Nevada'
start_datetime = '2002-01-10 00:00:00'
end_datetime = '2003-06-28 01:00:00'
model_name = 'prms'

# create XML FGDC-standard metadata that gets included in VW metadata
fgdc_metadata = make_fgdc_metadata(input_file, None, new_mr_uuid,
    start_datetime, end_datetime, model=model_name)

# create VW metadata
watershed_metadata = metadata_from_file(input_file, parent_uuid,
    new_mr_uuid, description, watershed_name, state,
    start_datetime=start_datetime, end_datetime=end_datetime,
    model_name=model_name, fgdc_metadata=fgdc_metadata)
response = vw_client.insert_metadata(watershed_metadata)
res = vw_client.dataset_search(model_run_uuid=new_mr_uuid)

**Comment by mtpain** [comment]
Do you have time to try something? I'm sorry I can't fix this right now, but I'm pretty sure the error is in the documentation. Would you please try to upload using the web app that's now online at https://vw.northwestknowledge.net/share/? I think it will work. If this does work, let me know and I will finally update the documentation. Then you can copy the code from the web app that does work for uploading data other that .tif.

Thanks for your help.

**Comment by lisapalathingal** [comment]
Ok, Matt, unfortunately it didn't work. I tried to create a resource using the web app https://vw.northwestknowledge.net/share. However, it is not creating a new resource. So, I ran vwplatform on localhost and uploaded netcdf files. But, the download link for netcdf files is not working. I know you are busy now but I just wanted to let you know about this. Please try to fix this when you get time and let me know. Thank you!

**Comment by mtpain** [comment]
OK, thanks for trying that, Lisa. I will hopefully take care of this by next Thursday.
