### ISSUE TITLE
netcdf services are missing from inserted netcdfs

### ISSUE THREAD

**Issue by mtpain** [tri-state-epscor/wcwave_adaptors#13]

**Comment by lisapalathingal** [comment]
Hi Matt,

I talked to John Erickson about empty services field issue and he told you figured out the issue. Could you please fix that issue so that Chase can try visualizing the NetCDF file?

Thank you,
Lisa

**Comment by ChaseCarthen** [comment]
This could be a result of the missing projection information within the generated netcdf's from what I have examined from the netcdf and opening in QGis and using gdalinfo.

One suggestion is to follow the grid_mapping cf convention that the gdal driver uses to pull out projection information (for ref. http://www.gdal.org/frmt_netcdf.html). 
Grid_Mapping convention: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch05s06.html (They have some example projection at this link as well.)
